name: Create PR when dependency graphs change

on:
  push:
    branches:
      - main
#      - ab/test-graphs-pr

jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Cache Gradle Caches
        uses: gradle/gradle-build-action@v3

      - name: Generate graphs
        run: ./gradlew :example:dependencyGraph
        if: success()

      # Get changed files list and set them to `outputs.changed`
      - id: get-pr-body
        run: |
          ./.github/ci-scripts/changed_files.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          add-paths: |
            dependencyGraph.md
            **/dependencyGraph.md
          commit-message: Updated dependency graphs
          branch: updated-dependency-graphs
          delete-branch: true
          title: Updated dependency graphs
          body: |
            ## Description
            Dependency graphs have been updated.

            List of changed files:
            ${{steps.get-pr-body.outputs.changed}}
